# Generated by Django 4.1.4 on 2022-12-14 02:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpapp', '0004_rename_title_category_category_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='post_count',
            field=models.IntegerField(),
        ),
    ]
